/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package endassessment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import sun.java2d.d3d.D3DRenderQueue;

/**
 *
 * @author USER
 */
public class AppointmentsPanel extends javax.swing.JPanel {
    Connection con = null;
    PreparedStatement pre = null;
    ResultSet res = null;
    String uname = Login.getUsername();
    String selectedAp;
    /**
     * Creates new form AppointmentsPanel
     */
    public AppointmentsPanel() {
        initComponents();
        con = dbConnection.connect();
        fill_appointments();
    }
    
    public void fill_appointments() {
        String sql = "select id,patient, time, ap_date,status from appointments where doctor='"+uname+"'";
        try {
            pre = con.prepareStatement(sql);
            res = pre.executeQuery();
            appointmentsTable.setModel(DbUtils.resultSetToTableModel(res));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 2);
        }
    }
    public void refresh(){
    fill_appointments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentsTable = new javax.swing.JTable();
        ApprApBtn = new javax.swing.JButton();
        lblAvatar2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));

        appointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(appointmentsTable);

        ApprApBtn.setBackground(new java.awt.Color(0, 204, 255));
        ApprApBtn.setForeground(new java.awt.Color(255, 255, 255));
        ApprApBtn.setText("Approve");
        ApprApBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApprApBtnActionPerformed(evt);
            }
        });

        lblAvatar2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblAvatar2.setForeground(new java.awt.Color(255, 255, 255));
        lblAvatar2.setText("Appointments");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ApprApBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(440, 440, 440))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAvatar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ApprApBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ApprApBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApprApBtnActionPerformed
     int row = appointmentsTable.getSelectedRow();
        String t = appointmentsTable.getModel().getValueAt(row, 0).toString();
        selectedAp = t;
        String sql = "UPDATE appointments SET status='approved' WHERE id='"+selectedAp+"'";
        try {
            // TODO add your handling code here:
            
            pre = con.prepareStatement(sql);
            pre.execute();
            JOptionPane.showMessageDialog(null, "Appointment approved successfully");
            refresh();
        } catch (SQLException ex) {
            Logger.getLogger(AppointmentsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        

;
        
    }//GEN-LAST:event_ApprApBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApprApBtn;
    private javax.swing.JTable appointmentsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatar2;
    // End of variables declaration//GEN-END:variables
}
