/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package endassessment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class BookAppointment1 extends javax.swing.JPanel {
    Connection con = null;
    PreparedStatement pre = null;
    ResultSet res = null;
    String uname = Login.getUsername();
    /**
     * Creates new form AdminProfile
     */
    public BookAppointment1() {
        initComponents();
        con = dbConnection.connect();
        BookApBtn.setEnabled(true);
        txtBookingDate.setMinSelectableDate(new Date());
        fill_slots();
        uname = Login.getUsername();
    }
    
       public void fill_slots() {

        String sql = "select * from slots";
        try {
            pre = con.prepareStatement(sql);
            res = pre.executeQuery();

            while (res.next()) {
                txtTime.addItem(res.getString("slot"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 2);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblAvatar2 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtDoctorTypes = new javax.swing.JComboBox<>();
        BookApBtn = new javax.swing.JButton();
        lblPassword1 = new javax.swing.JLabel();
        txtTime = new javax.swing.JComboBox<>();
        lblPassword2 = new javax.swing.JLabel();
        txtDoctors = new javax.swing.JComboBox<>();
        txtBookingDate = new com.toedter.calendar.JDateChooser();

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lblAvatar2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblAvatar2.setForeground(new java.awt.Color(255, 255, 255));
        lblAvatar2.setText("Book Appointment Here");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Appointment Date");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Select Doctor Type");

        txtDoctorTypes.setBackground(new java.awt.Color(153, 153, 153));
        txtDoctorTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor Type", "cardiologist", "pediatrician", "ophthalmologist", "ent", "dentist", "general" }));
        txtDoctorTypes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtDoctorTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorTypesActionPerformed(evt);
            }
        });

        BookApBtn.setBackground(new java.awt.Color(0, 204, 255));
        BookApBtn.setForeground(new java.awt.Color(255, 255, 255));
        BookApBtn.setText("Book");
        BookApBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookApBtnActionPerformed(evt);
            }
        });

        lblPassword1.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblPassword1.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword1.setText("Time");

        txtTime.setBackground(new java.awt.Color(153, 153, 153));
        txtTime.setSelectedIndex(-1);
        txtTime.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        lblPassword2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblPassword2.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword2.setText("Available Doctors");

        txtDoctors.setBackground(new java.awt.Color(153, 153, 153));
        txtDoctors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Cardiologist", "2 - Pediatrician", "3 - Ophthalmologist", "4 - ENT", "5 - Dentist", "6 - General" }));
        txtDoctors.setSelectedIndex(-1);
        txtDoctors.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDoctorTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword)
                    .addComponent(lblUsername)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword1)
                    .addComponent(txtDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword2))
                .addGap(184, 184, 184))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(lblAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(BookApBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvatar2)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addGap(18, 18, 18)
                .addComponent(txtDoctorTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword2)
                .addGap(18, 18, 18)
                .addComponent(txtDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addGap(18, 18, 18)
                .addComponent(txtBookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BookApBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BookApBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookApBtnActionPerformed
        if (txtDoctorTypes.getSelectedItem().equals("Select Doctor Type")) {
            JOptionPane.showMessageDialog(null, "Please selector Doctor Type");
        } else if (txtDoctors.getSelectedItem().equals("Select Doctor")) {
            JOptionPane.showMessageDialog(null, "Please selector Doctor");
        } else if (txtBookingDate.getDate().toString().equals("")) {
            JOptionPane.showMessageDialog(null, "Please select date");
        } else if (txtTime.getSelectedItem().equals("Select Time")) {
            JOptionPane.showMessageDialog(null, "Please select Time");
        } else {

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(txtBookingDate.getDate());

            String sql2 = "SELECT * FROM appointments WHERE ap_date='" +date+ "' AND time='" + txtTime.getSelectedItem().toString() + "' AND doctor='" + txtDoctors.getSelectedItem().toString() + "'";
            try {
                pre = con.prepareStatement(sql2);
                res=pre.executeQuery();
                if (res.next()) {
                    JOptionPane.showMessageDialog(null, "The date and time occupied, please select a different date and time");

                } else {
                    String sql = "insert into appointments (patient,doctor, doctor_type,ap_date,time) values ('" +uname+ "',"
                    + "'" + txtDoctors.getSelectedItem() + "','" + txtDoctorTypes.getSelectedItem() + "','" + date + "','" + txtTime.getSelectedItem() + "')";
                    pre = con.prepareStatement(sql);
                    pre.execute();
                    JOptionPane.showMessageDialog(null, "Booking Successfully done", "Success", 1);
                    
                    

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error while searchig for Booking", 2);
            }

        }
    }//GEN-LAST:event_BookApBtnActionPerformed

    private void txtDoctorTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorTypesActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM users WHERE type='" + txtDoctorTypes.getSelectedItem() + "'";
        try {
            pre = con.prepareStatement(sql);
            res = pre.executeQuery();
            txtDoctors.removeAllItems();
            while (res.next()) {
                txtDoctors.addItem(res.getString("username"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 2);
        }
    }//GEN-LAST:event_txtDoctorTypesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookApBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAvatar2;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblUsername;
    private com.toedter.calendar.JDateChooser txtBookingDate;
    private javax.swing.JComboBox<String> txtDoctorTypes;
    private javax.swing.JComboBox<String> txtDoctors;
    private javax.swing.JComboBox<String> txtTime;
    // End of variables declaration//GEN-END:variables
}
